name: Update master
on:
  push:
    branches:
      - main-test
jobs:
  update_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main-test
      - name: Update master
        run: |-
          set -euxo pipefail
          git branch -f master-test main-test
          git push -f origin main-test:main-test
